### ISSUE TITLE
Issue in mime sub-type compatibility test

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester#15]
I'm facing a problem where:

```
application/vnd.unbounce.test.v1+json
```

is not detected as being compatible with:

```
application/json
```

although it should.

Because of this issue, I receive:

```
No SchemaValidator found for media type 'application/vnd.unbounce.test.v1+json'
```

Playing with `guru.nidi.ramltester.util.MediaType`, I indeed see that:

```
MediaType
    .valueOf("application/vnd.unbounce.test.v1+json")
    .isCompatibleWith(MediaType.valueOf("application/json"))
```

returns `false`, which prevents the `RestassuredSchemaValidator` to be picked.

It would be great if this issue could be fixed.

**Comment by ddossot** [comment]
Any hope for a `0.0.8` release soon-ish? Thanks!

**Comment by nidi3** [comment]
done

**Comment by ddossot** [comment]
Amazing, thanks a whole bunch!

**Comment by nidi3** [comment]
You're welcome ;)
