### ISSUE TITLE
Properties of traits are not processed correctly

### ISSUE THREAD

**Issue by nidi3** [nidi3/raml-tester#16]
Maybe also resourceTypes?

**Comment by nidi3** [comment]
cannot reproduce

**Comment by ddossot** [comment]
I use traits and resource types extensively: what was the issue? Maybe I can test it again for you and then you can decide if you keep open or close this.

**Comment by nidi3** [comment]
This was reported by another user, but I was never able to reproduce anything.
Thanks for the confirmation that you too have no issues with traits.

I'll close the issue.
