### ISSUE TITLE
Allow X- headers to be ignored

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester#19]
This is more a feature request than an issue.

RAML Tester reports lots of issues with `X-` headers like the following (coming via the proxy):

        "Header 'X-Runtime' on action(GET /accounts) is not defined",
        "Header 'X-Instance-Id' on action(GET /accounts) is not defined",
        "Header 'X-Server-Instance' on action(GET /accounts) is not defined",
        "Header 'X-UA-Compatible' on action(GET /accounts) is not defined",
        "Header 'X-Request-Id' on action(GET /accounts) is not defined",
        "Header 'X-Powered-By' on action(GET /accounts) is not defined"

These headers are not in the RAML spec and won't be: they are added by servers and middlewares and are not really part of the API spec.

So it would be great to be able to tell RAML Tester to ignore `X-*` headers.

**Comment by nidi3** [comment]
I see the point. 
Just thinking if there are other elements that could make sense to ignore.

**Comment by ddossot** [comment]
I've tested this via the new `-i` option in RAML Tester Proxy and it works flawlessly. Thank you very much for this addition :bow:
