### ISSUE TITLE
NullPointerException when the response does not contain a body

### ISSUE THREAD

**Issue by rikard3000** [nidi3/raml-tester#30]
guru.nidi.ramltester.httpcomponents.HttpComponentsUtils#buffered(org.apache.http.HttpResponse) causes a NullPointerException when the response does not contain a body, as when a 204 is returned. Looks like this is incorrect:

```
        final HttpEntity entity = response.getEntity();  //entity may be null
        if (!entity.isRepeatable()) {
```

Raml:
```
    post:
      body:
        ...
      responses:
        204:
```

**Comment by rikard3000** [comment]
Do you know when there will be a release with this fix in?

**Comment by nidi3** [comment]
now :)

**Comment by rikard3000** [comment]
Sweetums
