### ISSUE TITLE
Bogus unusedResources error when a path has no method

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester#46]
With this RAML structure:
```yaml
/users:
  /self:
    get:
  /{user_id}:
    get:
```
I get the following error:
```json
  "unusedResources": [
    "/users"
  ]
```
after running tests on the API.
As you can see, there's no method defined at `/users` level, only in the levels below can the `get` method be found. I think that in this case, RAML Tester should not consider this resource as being unused because it can't be used at all...

**Comment by ddossot** [comment]
Woah thanks a lot for the quick fix! Any chance to get a release train (tester+proxy) soon-ish?

As a workaround I had to write my RAML like this:
```yaml
/users/self:
  get:
/users/{user_id}:
  get:
```
but I'd rather use the proper hierarchical form :wink:

**Comment by nidi3** [comment]
Hope to do a release by the end of this week

**Comment by ddossot** [comment]
Happy to confirm the issue is gone with version `0.8.4` :+1:
