### ISSUE TITLE
Header names are case sensitive

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester#47]
We have the following API definition:
```yaml
    put:
      headers:
        If-Match:
          description: |
            xxx
          type: string
          required: true
      body:
        schema: xxx
      responses:
        200:
          description: xxx
          headers:
            ETag:
              type: string
              description: xxx
          body:
            schema: xxx
```
As you can see we specify `If-Match` and `ETag` because they play an important role on this resource and we want to attach a clear documentation to these request and response headers.

When we test our API, we keep getting this kind of violations:

    Unused request headers: ("If-Match in PUT /xxx")
    Unused response headers: ("ETag in PUT /xxx -> 200")

But our test requests and server responses do have these headers. I think this is due to the fact that these headers are in the `DefaultHeaders` structure: https://github.com/nidi3/raml-tester/blob/master/src/main/java/guru/nidi/ramltester/core/RamlChecker.java#L39-L40

**Comment by nidi3** [comment]
I cannot reproduce this.
What happens if you change the header name to a non-default name?

**Comment by ddossot** [comment]
I did this and realize that I was wrong in my diagnostic. The issue is way more trivial than that.

It turns out RAML Tester is case sensitive for HTTP headers, which is the root cause of the problem. Our client sends test requests with headers in lower case, ie `if-match`, and our server responds with headers in lower case, ie `etag`. If I change the RAML spec to declare the headers in lower case, the issue goes away!

HTTP headers names are case insensitive per spec so I think this is a bug that needs fixing.
