### ISSUE TITLE
Cannot resolve relative schema references in JSON schemas

### ISSUE THREAD

**Issue by greenrd** [nidi3/raml-tester#49]
We have a RAML file that references some JSON schema files, and one of the JSON schema files references another JSON schema file. The latter reference cannot be resolved by the JSON schema validator - even when we pass in a custom loader to SchemaValidators.withloader to resolve such references (the custom loader is never called).

**Comment by ddossot** [comment]
I have a similar scenario working fine. You need to make sure that the schemas - at least the ones directly referred to from RAML - have a proper id attribute - ie a full URI that points to them.

**Comment by greenrd** [comment]
I've got it working now, with some custom code that calls `addPathRedirect` on the `URITranslatorConfiguration`. The problems with the existing code if you want to do a path redirection from a URI to local files were:

1. If you include an `id` in the schema file, the loaders are never activated because the JSON schema validator resolves relative schema refs relative to the value of `id`, as the spec requires, so they become absolute URIs.

2. If you *don't* include an `id` in the schema file, the loaders are activated, but they only see the filename not the path, so they can't do resolution correctly in a hierarchical directory structure.

So, because of problem 2, I thought that it was better to call `addPathRedirect`, even though this creates a dependency from my code to the particular JSON validator implementation.

**Comment by nidi3** [comment]
Hm, is there something I can/should do here, or can I close the issue?

**Comment by greenrd** [comment]
I think it would be quite common to want to set a path redirect from a URI to a local directory for local development, so I suggest adding a method to your API to make it easier to set up a path redirect. At the moment it can be done but it's not very convenient.

**Comment by nidi3** [comment]
I adapted the way includes are handled: If a `.json` file is included which has a `$schema` property but no `id` property, `id` is set to point to the effective location of the json file. This way, relative `$ref`s are resolved correctly.

It's available in version 0.8.5-SNAPSHOT from this repository: https://oss.sonatype.org/content/repositories/snapshots

What do you think about?

**Comment by greenrd** [comment]
I am away for the next 4 days, but I'll try it out when I get back.

**Comment by greenrd** [comment]
Yes, that works for me - thanks!
