### ISSUE TITLE
Testing apps with a servlet-per-resource fails

### ISSUE THREAD

**Issue by lewisd32** [nidi3/raml-tester#50]
We've been using (or trying to use) raml-tester for two different projects.  It's working great on one project, but we're having troubles with the second project.  The first project uses Jersey, so there's a single servlet, mapped to `/api`, with all the resources served up via it, eg `/api/someApiResource`.  This works fine.

The project we have trouble with is a legacy project, that has a servlet per resource.  Because of this, there is no path-info on requests to the resources.  That's causing problems with this code from `ServletRamlRequest`:

```
    @Override
    public String getRequestUrl(String baseUri) {
        return baseUri == null
                ? request().getRequestURL().toString()
                : (baseUri + request().getPathInfo());
    }
```

This results in "baseUrinull" as the requestUrl.  Because of this, raml-tester is unable to match any of the resources being requested by our API tests.

I'm not sure what the best solution to this is, but I wondered if returning `request().getRequestURL().toString()` when path-info is null would do the trick safely?
```
    @Override
    public String getRequestUrl(String baseUri) {
        String pathInfo = request().getPathInfo();
        return baseUri == null || pathInfo == null
                ? request().getRequestURL().toString()
                : (baseUri + pathInfo);
    }
```
I've verified that the above change passes a `mvn clean install`, at least, and seems to fix our usecase.

**Comment by nidi3** [comment]
This seems to be a valid solution... going to test it.

**Comment by nidi3** [comment]
I guess it should be

    final String pathInfo = request().getPathInfo() == null ? "" : request().getPathInfo();
    return baseUri == null
            ? request().getRequestURL().toString()
            : (baseUri + pathInfo);

Does this also fix our usecase?

**Comment by lewisd32** [comment]
Unfortunately, it doesn't.
```
Expected: Unused resources to be empty
     but: was <[/someResourceServlet]>
```
In our case, baseUri is `http://localhost:port/appname`, and `request().getServletPath()` returns `/someResourceServlet`.  The RAML references a number of servlets, each one of which is a resource.  Since this isn't included in the baseUri, and isn't in the path-info, I think the fix would need to either incorporate `getServletPath()` (with all the appropriate null checking), or fall-back to `getRequestUrl()`.

**Comment by nidi3** [comment]
Ok, now I understand. In your situation, the servletPath is missing.
I think we need one more flag to handle this, because `getPathInfo()==null` does not automatically mean we should add the servletPath

**Comment by nidi3** [comment]
I added a flag to `RamlDefinition.assumingBaseUri` can you verify that the problem is solved?
You can use the version 0.8.5-SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots

**Comment by lewisd32** [comment]
Yes, it looks like changing `ramlDef.assumingBaseUri(baseUri)` to `ramlDef.assumingBaseUri(baseUri, true)` fixes it with 0.8.5-SNAPSHOT. :+1:

**Comment by lewisd32** [comment]
Will you be releasing 0.8.5 with this fix in the near future?

**Comment by nidi3** [comment]
Yes, I hope I can make a release next week end
