### ISSUE TITLE
Support RAML 1.0

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester#55]
RAML 1.0 is about to be finalized, as announced here: http://blog.raml.org/raml-1-0-final-candidate/

The blog post shows examples of what's new and coming in 1.0, which is a good start to start thinking/preparing support for it in RAML Tester :wink:

**Comment by nidi3** [comment]
Saw it... I'm mentally preparing myself :jack_o_lantern:

**Comment by ddossot** [comment]
FYI a new Java parser is being built: https://github.com/raml-org/raml-java-parser-2/ This library also offers support for RAML Types.

**Comment by ihr** [comment]
:+1:

**Comment by atdiff** [comment]
Has this project been updated to handle RAML 1.0 or are there plans to do so soon?

**Comment by nidi3** [comment]
There is work in progress for a new java based RAML 1.0 parser. As soon as it comes out, I'm going to work on 1.0 support.

**Comment by donovankim** [comment]
+1

**Comment by sichvoge** [comment]
@nidi3 we just published a pre-release version to a branch in [here](https://github.com/raml-org/raml-java-parser-2/tree/native). There are still some gaps that needs to get closed which we currently work on, but you can use it already to start supporting it ;)

**Comment by benleibert** [comment]
+1

**Comment by marcincharezinski** [comment]
Any updates on this @nidi3  ? It would be great if you could point some release date with this feature.

**Comment by nidi3** [comment]
I started working on it yesterday, Here is an overview of the progress: https://github.com/nidi3/raml-tester/blob/raml-parser-2/1.0-support.md
I can't give a release date, but a first (incomplete) version should come out quickly.

**Comment by sichvoge** [comment]
Hi Stefan, thanks for the update. Just a quick comment on the list. The `types` node does not fully replace the `schema` node, but is something complementary. Both nodes are mutual exclusive and synonymous.

**Comment by jrusiecki** [comment]
+1
Great effort.
As RAML 1.0 IS superior, any (even *first*) version is welcome.

**Comment by leetcooper** [comment]
Hi Stefan, I am in the process of choosing between RAML and SWAGGER for my REST API documentation.

My decision will probably be decided on your very cool RAML tester but obviously not using 1.0 on a greenfield project would not be a good idea.  I see that you have a specific branch for this work.  Is there any reason you would discourage me from pulling and building this branch for an initial investigation for use in my project?

Thanks Lee

**Comment by nidi3** [comment]
Hi @leetcooper 
Did you already checkout the branch? I would say "why not" and would apreciate any feedback you could give.

I hope I'll find some time soon to really release a first version of it.

**Comment by nidi3** [comment]
Finally, there is a [first version](https://github.com/nidi3/raml-tester/releases/tag/raml-tester-0.9.0) supporting RAML 1.0 available!

**Comment by benleibert** [comment]
Awesome! Thank you very much, Stefan! We’re currently using your fine tool, and would love to move to v1.0 of RAML.

**Comment by sichvoge** [comment]
wohooo @nidi3 nice!

**Comment by javavenkats5** [comment]
Hi nidi3,
When can we expect full supporting version of RAML1.0? any dates please? Eagerly waiting...
