### ISSUE TITLE
Requests violations are reported for headers defined in security scheme

### ISSUE THREAD

**Issue by ddossot** [nidi3/raml-tester#63]
RAML Tester reports request violations for requests that contain headers even if they are specified in the `describedBy` map of the custom security scheme.

It would be nice to recognize these headers and not report request violations.

**Comment by nidi3** [comment]
Can you give an example please. 
`SecurityTest` checks such cases and it does not fail.

**Comment by ddossot** [comment]
Here is an example:

```yaml
securitySchemes:
  - custom-sec:
      type: x-custom-sec
      describedBy:
        headers:
          X-Custom-Token:
            type: string
            required: true
          X-Custom-Context:
            type: string
            required: false
        responses:
          401:
            description: |
              If the authentication failed.
```
If I send a request with the `X-Custom-Context` header, it gets reported as a request violation.

**Comment by nidi3** [comment]
To me this looks exactly as this test:
https://github.com/nidi3/raml-tester/blob/master/src/test/java/guru/nidi/ramltester/SecurityTest.java#L42-L48
What are you doing differently?

**Comment by ddossot** [comment]
OK, I've figured out the difference.

Basically, with the above config, if I do provide `X-Custom-Context` but omit to provide the required `X-Custom-Token`, I get a bogus error saying `[Header 'X-Custom-Context' on action(...) is not defined]`. Basically it complains about the second optional header being provided instead of complaining about the first header being missing.

I've step debugged into `ParameterChecker` and could see that for one iteration, the proper error (`Header 'X-Custom-Token' on action(...) is required but not found`) is added to `violations`, but then quickly removed and replaced by the bogus violation.

**Comment by nidi3** [comment]
Ok, thanks to your analysis, I understand. 
Multiple security schemes can be applied to the same endpoint. The checker tries to determine which one should be used. It does not find `X-Custom-Token`, therefore eliminates `custom-sec` and does then complain about the unknown `X-Custom-Context`. 
I guess you only have the `custom-sec` applied, so eliminating it is not valid.

**Comment by ddossot** [comment]
OK, I understand better what's going on there.

In my case, there's only one `securitySchemes` defined and it is applied to this particular resource, so I reckon you could have a bypass in the logic when there's no ambiguity about the scheme that's in use?

**Comment by nidi3** [comment]
Exactly this. Working on it.

**Comment by ddossot** [comment]
Thank you sir, very appreciated!

So... release time? :sweat_smile:

**Comment by nidi3** [comment]
Release time! :tada:
