### ISSUE TITLE
"Root definition has no description" message when validating RAML

### ISSUE THREAD

**Issue by martinpaoloni** [nidi3/raml-tester#64]
Hi. I'm trying to validate a very simple RAML file with RAML Tester.
I have this code in my test case:
```java
RamlDefinition api = RamlLoaders.fromClasspath(getClass()).load("concur_minimal.raml");
Assert.assertThat(api.validate(), validates());
```
The assertion fails with this message:
```
java.lang.AssertionError: 
Expected: To be empty
     but: 
Validation violations:
  - Root definition has no description
```

What exactly does this mean? Should I have a ```description:``` tag at the top level of my RAML? If I do this, the RAML Editor in Anypoint Studio complains, and RAML Tester also fails:
```
java.lang.RuntimeException: Builder not found for <NodeTuple keyNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=description)>; valueNode=<org.yaml.snakeyaml.nodes.ScalarNode (tag=tag:yaml.org,2002:str, value=Concur API definition)>>
	at org.raml.parser.builder.DefaultTupleBuilder.getBuilderForTuple(DefaultTupleBuilder.java:68)
	at org.raml.parser.visitor.YamlDocumentBuilder.onTupleStart(YamlDocumentBuilder.java:272)
	at guru.nidi.ramltester.RelativeJsonSchemaAwareRamlDocumentBuilder.onTupleStart(RelativeJsonSchemaAwareRamlDocumentBuilder.java:65)
```

Any ideas? Thanks in advance.

**Comment by nidi3** [comment]
Hi 
You are almost correct. As of https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#user-documentation the format is
```
documentation:
    - title: ...
      content: ...
```

Note that you can customize what should be validated with
`Assert.assertThat(api.validator().withChecks(...).validate(), validates());`

**Comment by martinpaoloni** [comment]
Awesome. Didn't realize you could configure the validator. Thanks @nidi3!
