### ISSUE TITLE
Schema inclusions not working?

### ISSUE THREAD

**Issue by KenLomax** [nidi3/raml-tester#68]
HI
The attached raml and test will fail if I do not have the two (empty) files, named precisely “tip” and “tips” (with no extension) alongside the api.raml

What I would expect, is that I can have the following in my api.raml entry:

schemas:
  - tip: !include schemas/tip.json  
  - tips: !include schemas/tips.json

and the two files tip.json and tips.json in the schemas folder, which lives alongside api.raml

Thanks

[Archive.zip](https://github.com/nidi3/raml-tester/files/295491/Archive.zip)

**Comment by nidi3** [comment]
What's the error message? stack trace?

**Comment by KenLomax** [comment]
Closed, reopened and refreshed my eclipse project, and the problem is no longer there, so cannot send stack trace(!)  I think it must have been a classpath issue - sorry for bothering you with it.  If it comes back, I'll report with the trace and error.
