### ISSUE TITLE
plans to support/consume rest-assured 3.x release bits

### ISSUE THREAD

**Issue by psura** [nidi3/raml-tester#75]
Hi: The latest supported version of rest-assured by raml-tester as seen in the pom dependency is 2.7 - https://github.com/nidi3/raml-tester/blob/master/pom.xml

We now have 3.x release bit of rest-assured with new namespace and potentially many non-backward compatible and deprecated changes as noted in the release notes here : 
https://github.com/rest-assured/rest-assured/wiki/ReleaseNotes30

Love to know the road map/ timeline for raml-tester to consume/ support the 3.x bits of rest-assured.

**Comment by nidi3** [comment]
Here you go
