### ISSUE TITLE
Validation results as POJOs instead of String

### ISSUE THREAD

**Issue by arielsegura** [nidi3/raml-tester#76]
Hi there,

In my case, I'm using raml-tester to validate requests against my raml not only for tests but also in runtime (by implementing a filter), so the output of this validation becomes the response for the client. 
The issue is that the response is not that good for a REST API. For instance:

Body does not match schema for action(POST /organizations/{organizationId}/projects) mime-type('application/json')
Content: {
   "description": "description",
   "type": "type"
}
Message: error: object has missing required properties (["name"])
   level: "error"
   schema: {"loadingURI":"#","pointer":""}
   instance: {"pointer":""}
   domain: "validation"
   keyword: "required"
   required: ["description","name","type"]
   missing: ["name"]

I wonder if it could be possible change the ValidationResults to be a set of POJOs - or something like that - so I can prepare a more elegant response or at least do something else with them, which is uncomfortable to do with these strings. 
I guess a POJO like com.github.fge.jsonschema.core.report.ProcessingMessage would be enough.

**Comment by nicolasgnr** [comment]
+1

**Comment by nidi3** [comment]
Now `RamlViolations.asMessages().getMessageObject()` returns a ProcessingReport if available. Is this ok for you?

**Comment by arielsegura** [comment]
I'd much rather an interface or something more accurate than Object. I created a pull request in order to show you the approach I had in mind:
https://github.com/nidi3/raml-tester/pull/77

This way, on my end, I'm able to receive both a RamlViolationMessage like this: 
`message: Body does not match schema for action(POST /v1/bla mime-type('application/json')
Content: {"dummy": "bla"}
Message: error: object has missing required properties (["name"])
    level: "error"
    schema: {"loadingURI":"#","pointer":""}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "required"
    required: ["name"]
    missing: ["name"]
`
(Which is the message raml-tester returns. These messages are still return on the asList() method.)

And also a specific object I can work with: 

raml violation cause (instance of RamlViolationCause): 
* cause.message: object has missing required properties (["name"]) 
* cause.asJson: {"level":"error","schema":{"loadingURI":"#","pointer":""},"instance":{"pointer":""},"domain":"validation","keyword":"required","message":"object has missing required properties ([\"name\"])","required":["name"],"missing":["name"]}

**Comment by nidi3** [comment]
Next iteration, based on your pull request

**Comment by arielsegura** [comment]
Any news on this?

**Comment by nidi3** [comment]
Sorry for the late answer.
It's implemented, see [RamlViolationMessage](../blob/master/src/main/java/guru/nidi/ramltester/core/RamlViolationMessage.java).

I'm going to release this this weekend.

**Comment by arielsegura** [comment]
Looks good!
